import Head from 'next/head'
import { Inter } from 'next/font/google'
import LayOut from '../../components/LayOut'
import Carousel from '../../container/Home/Carousel'
import TopFeatures from '../../container/Home/Top-Feature'
import Service from '../../container/Home/Service'
import FeatureTwo from '../../container/Home/Featuer-Two'
import Sponsorship from '../../container/Home/Sponsorship'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
  
    <LayOut>
      <Head>
        <title>Home Again</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className='home-page '>
        <Carousel/>
        <TopFeatures/>
        <FeatureTwo/>
        <Sponsorship/>
      </div>
    </LayOut>
      

  )
}
