import Head from 'next/head'
import { Inter } from 'next/font/google'
import LayOut from '../../components/LayOut'
import TopFeatures from '../../container/Home/Top-Feature'
import FeatureTwo from '../../container/Home/Featuer-Two'
import Sponsorship from '../../container/Home/Sponsorship'
import Gallery from './activities'
import { HeaderSlider } from '../../container/Home/HeaderSlider'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
  
    <LayOut>
      <Head>
        <title>Home Again</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <HeaderSlider/>
      <div className='home-page container'>
        <TopFeatures/>
        <FeatureTwo/>
        <Sponsorship/>
        <Gallery/>
      </div>
    </LayOut>
      

  )
}
